// <auto-generated />
using System;
using API_Sample.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Sample.Data.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260422040658_V2_RubberPlantation_Schema")]
    partial class V2_RubberPlantation_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Sample.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("account_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("use_name");

                    b.HasKey("Id");

                    b.ToTable("Account", null, t =>
                        {
                            t.HasComment("fruit-to-seed conversion rate");
                        });
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Allowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowanceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("allowance_type_id");

                    b.Property<decimal>("CalculatedAmount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("calculated_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DaysOrAmount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("days_or_amount");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("year_month");

                    b.HasKey("Id");

                    b.HasIndex("AllowanceTypeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("allowance");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.AllowanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("DefaultRate")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("default_rate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("allowance_type");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbsentDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("absent_days");

                    b.Property<string>("AttendanceStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("attendance_status");

                    b.Property<decimal>("CareDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("care_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DoubleCutDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("double_cut_days");

                    b.Property<decimal>("DoubleCutSunday")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("double_cut_sunday");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("HardshipDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("hardship_days");

                    b.Property<decimal>("LeaveDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("leave_days");

                    b.Property<decimal>("RegularDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("regular_days");

                    b.Property<decimal>("SickDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("sick_days");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("SundayDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("sunday_days");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_days");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("year_month");

                    b.Property<decimal>("YoungTreeDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("young_tree_days");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "YearMonth")
                        .IsUnique();

                    b.ToTable("attendance");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int")
                        .HasColumnName("changed_by");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("table_name");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.CostAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("allocated_amount");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int")
                        .HasColumnName("cost_center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int")
                        .HasColumnName("payroll_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("PayrollId");

                    b.ToTable("cost_allocation");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("accounting_code");

                    b.Property<decimal?>("AllocationRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("allocation_rate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("cost_center");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("department");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.DrcRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DrcRawLatex")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("drc_raw_latex");

                    b.Property<decimal?>("DrcReference")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("drc_reference");

                    b.Property<decimal?>("DrcRope")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("drc_rope");

                    b.Property<decimal?>("DrcSerum")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("drc_serum");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("note");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int?>("TramId")
                        .HasColumnType("int")
                        .HasColumnName("tram_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("year_month");

                    b.HasKey("Id");

                    b.HasIndex("TramId");

                    b.HasIndex("YearMonth", "TramId")
                        .IsUnique()
                        .HasFilter("[tram_id] IS NOT NULL");

                    b.ToTable("drc_rate");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameLocal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name_local");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("InsuranceIncluded")
                        .HasColumnType("bit")
                        .HasColumnName("insurance_included");

                    b.Property<string>("Msnv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("msnv");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TechnicalGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("technical_grade");

                    b.Property<int>("TramId")
                        .HasColumnType("int")
                        .HasColumnName("tram_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Msnv")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.HasIndex("TramId");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("MediumUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("medium_url");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("RefId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("ref_id");

                    b.Property<string>("RelativeUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("relative_url");

                    b.Property<int?>("SerialId")
                        .HasColumnType("int")
                        .HasColumnName("serial_id");

                    b.Property<string>("SmallUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("small_url");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Timer")
                        .HasColumnType("datetime")
                        .HasColumnName("timer");

                    b.HasKey("Id")
                        .HasName("PK__Images__3213E83F47534C37");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_salary");

                    b.Property<decimal>("Bhxh")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("bhxh");

                    b.Property<decimal>("Bhyt")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("bhyt");

                    b.Property<DateTime?>("CalculatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("calculated_at");

                    b.Property<int?>("CalculatedBy")
                        .HasColumnType("int")
                        .HasColumnName("calculated_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("gross_salary");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("income_tax");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("net_salary");

                    b.Property<string>("PayrollStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payroll_status");

                    b.Property<decimal>("PerformanceCoef")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("performance_coef");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAllowances")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_allowances");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_deductions");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("WorkingDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("working_days");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("year_month");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "YearMonth")
                        .IsUnique();

                    b.ToTable("payroll");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.PayrollDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("item_code");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int")
                        .HasColumnName("payroll_id");

                    b.Property<int>("Phase")
                        .HasColumnType("int")
                        .HasColumnName("phase");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PayrollId");

                    b.ToTable("payroll_detail");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Grade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("grade");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<decimal?>("OutputKg")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("output_kg");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("year_month");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "YearMonth")
                        .IsUnique();

                    b.ToTable("performance");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("position");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameSlug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name_slug");

                    b.Property<double?>("RatioTransfer")
                        .HasColumnType("float")
                        .HasColumnName("ratio_transfer")
                        .HasComment("Tỉ lệ chuyển đổi");

                    b.Property<string>("Remark")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("remark");

                    b.Property<int?>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("Product", null, t =>
                        {
                            t.HasComment("fruit-to-seed conversion rate");
                        });
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CarryDryKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("carry_dry_kg");

                    b.Property<decimal>("CarryOverKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("carry_over_kg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("DrcRaw")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("drc_raw");

                    b.Property<decimal?>("DrcSerum")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("drc_serum");

                    b.Property<decimal>("DryLatexKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("dry_latex_kg");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<decimal>("RawLatexKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("raw_latex_kg");

                    b.Property<decimal>("RopeLatexKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rope_latex_kg");

                    b.Property<decimal>("SerumKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("serum_kg");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TechGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("tech_grade");

                    b.Property<decimal>("TotalPayKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_pay_kg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("year_month");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "YearMonth")
                        .IsUnique();

                    b.ToTable("production");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.SalaryScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("coefficient");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("grade");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("TramId")
                        .HasColumnType("int")
                        .HasColumnName("tram_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TramId", "Grade", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("salary_scale");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.SystemParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("DataType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("ParamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("param_code");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("param_name");

                    b.Property<decimal>("ParamValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("param_value");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ParamCode", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("system_parameter");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Tram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tram");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Allowance", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.AllowanceType", "AllowanceType")
                        .WithMany("Allowances")
                        .HasForeignKey("AllowanceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Sample.Data.Entities.Employee", "Employee")
                        .WithMany("Allowances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllowanceType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Attendance", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.CostAllocation", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.CostCenter", "CostCenter")
                        .WithMany("CostAllocations")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Sample.Data.Entities.Payroll", "Payroll")
                        .WithMany("CostAllocations")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostCenter");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Department", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.DrcRate", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Tram", "Tram")
                        .WithMany()
                        .HasForeignKey("TramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tram");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Employee", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API_Sample.Data.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API_Sample.Data.Entities.Tram", "Tram")
                        .WithMany("Employees")
                        .HasForeignKey("TramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("Tram");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Payroll", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.PayrollDetail", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Payroll", "Payroll")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Performance", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Employee", "Employee")
                        .WithMany("Performances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Production", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Employee", "Employee")
                        .WithMany("Productions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.SalaryScale", b =>
                {
                    b.HasOne("API_Sample.Data.Entities.Tram", "Tram")
                        .WithMany("SalaryScales")
                        .HasForeignKey("TramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tram");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.AllowanceType", b =>
                {
                    b.Navigation("Allowances");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.CostCenter", b =>
                {
                    b.Navigation("CostAllocations");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Employee", b =>
                {
                    b.Navigation("Allowances");

                    b.Navigation("Attendances");

                    b.Navigation("Payrolls");

                    b.Navigation("Performances");

                    b.Navigation("Productions");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Payroll", b =>
                {
                    b.Navigation("CostAllocations");

                    b.Navigation("PayrollDetails");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("API_Sample.Data.Entities.Tram", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SalaryScales");
                });
#pragma warning restore 612, 618
        }
    }
}
